# Generated by Django 5.0.6 on 2024-06-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercard',
            name='discount',
            field=models.SmallIntegerField(default=0),
        ),
    ]
